name: ExtUtils-MakeMaker
version: 6.06_03
version_from: lib/ExtUtils/MakeMaker.pm
installdirs: perl
requires:
File::Spec: 0.8
File::Basename: 0
DirHandle: 0
Pod::Man: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.06_03
