name: smoke-windows-cygwin-amd64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
        with:
            fetch-depth: 10
      - name: Set up Cygwin
        run: |
          choco install cygwin cyg-get
          cyg-get cygwin-devel gcc-core gcc gcc-g++ make cygwin64-w32api-headers binutils libtool git perl libcrypt-devel libnsl-devel
      - name: Find out environment
        shell: cmd
        run: |
          dir c:\tools\cygwin
          path
          echo "c:\tools\cygwin\bin;c:\tools\cygwin\usr\bin" ^| Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
          path
      - name: Check out again, using Cygwin git, to reset file permissions
        shell: cmd
        run: git checkout --force
      - name: Configure
        shell: cmd
        run: perl Makefile.PL
      - name: Build
        shell: cmd
        run: make
      - name: Run Tests
        shell: cmd
        run: make test
